donkey=../donkey
server=../server
client=../client
cli=../command
version=4.6.0

# This value is used as the modified time for the files inside of jar, zip, and war files
archive.entry.date=1999-01-01T00:00:00.000Z
